services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sthack-admin
      MONGO_INITDB_ROOT_PASSWORD: sthack-password
      MONGO_INITDB_DATABASE: sthack
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: sthack-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: sthack-password
      ME_CONFIG_MONGODB_URL: mongodb://sthack-admin:sthack-password@mongo:27017/

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  mongo-data:
